# Change baseurl before deploy
baseurl      = "https://ottercoconut.github.io"
locale = "zh-CN"
title        = "边个濑椰のBlog"

# Theme i18n support
# See all available values at https://github.com/CaiJimmy/hugo-theme-stack/tree/master/i18n
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

[pagination]
    pagerSize = 5

[outputFormats.GoogleSitemap]
    mediaType = "application/xml"
    baseName = "google-sitemap"
    isPlainText = true
    notAlternative = true

[outputs]
    home = ["HTML", "RSS", "GoogleSitemap"]

[taxonomies]
category = "categories"
tag = "tags"
